language: node_js
node_js:
  - 7
  - 6
  - 5
after_success:
  - NODE_ENV=production npm run build
  - semantic-release pre && npm publish && semantic-release post
notifications:
  email: false
sudo: false
